#!url=https://raw.githubusercontent.com/kane-abbe/shadowrocket/main/tiktok/tiktok.module
#!name=TikTokUS
#!desc=TiktokUS解锁测试

[Rule]
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/TikTok/TikTok.list,PROXY

[URL Rewrite]
(?<=&mcc_mnc=)4 2 307
(?<=_region=)CN(?=&) US 307
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302


[MITM]
hostname = %APPEND% *.byteoversea.com,*.tik-tokapi.com,*.tiktokv.com
